# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  pod 'sspadkit', :path => '../../'
  #pod 'sspadkit', :git => 'https://github.com/gowittechnology/ssp-ios-sdk-public.git', :branch => '1.0.0'
  # Pods for example

end
